### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by DotDebian** [PatoTheBest/SimplisticEconomy#3]
Is the plugin, in it's current state, stable ?
I would like to use it with a 500+ player base.

Thanks

**Comment by PatoTheBest** [comment]
Hello @DotDebian,

I will address this question from a technical point of view talking about the internal workings and current limitations with vault. First of all, by 500+ I'd imagine you are talking about 500+ concurrent players with multiple server instances. 

I'm gonna start talking about the plugin Vault, a widely used plugin that makes interacting with economy plugins easier. The issue with Vault is that everything has to be done synchronously as it doesn't have any async/callback support. This plugin in order to prevent lag by constantly querying the database, it caches the player's data on join and saves the data when there are modifications (deposit/withdraws), so consulting the balance is done by consulting the cache. 

This approach could be both good and bad depending on the use case of the plugin. If you are using on one server instance, then there is nothing to worry about. If there are multiple instances, since it uses cache for consulting the player's balance, there could be a desync where the player is on *server b*, but *server a* takes money from the player and then the player on *server b* has an outdated balance. It wouldn't be an issue if it's money being added, but in the case of an offline buy shop (ex chestshop), it could make the player have a negative balance.

Other than this, you shouldn't really have performance issues and you can feel free to test it, use it and report any problems if you find. This plugin has been in use for over 3 years now in different gamemodes on a server I develop for and we haven't run into issues.

Regards,
Pato

**Comment by DotDebian** [comment]
Can you please add me on Discord ? `~Deb'#0001`.
Went through the code and I can't find out why aren't Vault PlaceholderAPI placeholders correctly working.

**Comment by PatoTheBest** [comment]
Hello, it says you are not accepting friend requests at this time.

**Comment by PatoTheBest** [comment]
Closing this due to no further response
